# Generated by Django 3.2.5 on 2021-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
