# Generated by Django 3.2.5 on 2021-07-17 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_auto_20210716_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='time',
        ),
        migrations.AddField(
            model_name='like',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
